import React from 'react';  
import { Link } from 'react-router-dom';
import { addClass, removeClass, enableScroll, isSafari } from '../helpers'; 

class Imprint extends React.Component {

	closeImprint(e) {
		e.preventDefault();
		const imprint = document.querySelectorAll('.js-module--imprint')[0];
		removeClass(imprint, 'is-visible');
		enableScroll(isSafari()); 
	}

	render() {
	
		return(
			<div className="module module--imprint js-module--imprint">
				<div className="centered-module mobile-pv+ pv++">
						<h1>Imprint</h1>

						<h2>Author</h2>
						<p>Stefan Kaltenegger<br/>
						Franziskanerplatz 11/11 <br/>
						8010 Graz<br/>
						
						<a href="mailto:stefan@stk.works">stefan@stk.works</a><br />
						<a href="http://stk.works">http://stk.works</a>
						</p>

						<h2>Disclaimer</h2>
						<p>Despite careful control, I take no responsibility for the content of external links. Solely their page owners are responsible the content of linked pages.</p>

						<h2>Google Analytics</h2>
						<p>This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. In case of activation of the IP anonymization, Google will truncate/anonymize the last octet of the IP address for Member States of the European Union as well as for other parties to the Agreement on the European Economic Area. Only in exceptional cases, the full IP address is sent to and shortened by Google servers in the USA. On behalf of the website provider Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage to the website provider. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser. However, please note that if you do this, you may not be able to use the full functionality of this website. Furthermore you can prevent Google’s collection and use of data (cookies and IP address) by downloading and installing the browser plug-in available under https://tools.google.com/dlpage/gaoptout?hl=en-GB.</p>
						
						<Link to="#" onClick={(e) => this.closeImprint(e)} className="close-link js-close-link">
							<svg viewBox="0 0 40 40">
								<circle cx="20" cy="20" r="17.63"/>
								<line x1="27.1" y1="27.1" x2="12.9" y2="12.9"/>
								<line x1="27.1" y1="12.9" x2="12.9" y2="27.1"/>
							</svg>
						</Link>
						
				</div>
				
			</div>
		)
	} 
}

export default Imprint;